### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by nguyenpbui** [ktr-hubrt/Codes-for-WSAL#15]
Firstly, thank you for your amazing work!
I want to ask about loss_3 and loss_5 in the attached picture. Are they in Equation 9 in your paper.
Can you please explain about this?

![image](https://user-images.githubusercontent.com/34409468/169443012-589f83d5-fa49-41df-8682-dfac548ecc90.png)

Thank you very much.

**Comment by zimengxueying** [comment]
> 

Hello, have you solved it?
